debug: true

server:
  port: 8080
  servlet:
    context-path: /demo

mybatis:
  mapperLocations: classpath*:mapper/**/*.xml

spring:
  profiles:
    active:  ${PROFILES_ACTIVE:dev}
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 8
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

logging:
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.boot.web.embedded.tomcat: INFO
    com.demo: ${LOG_LEVEL:DEBUG}
